services:
  mysql:
    image: mysql:9.1.0
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    env_file:
      - .env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "8080:80"